### ISSUE TITLE
Error on cascade delete in MySQL 8

### ISSUE THREAD

**Issue by samuelbray32** [datajoint/datajoint-python#1110]
### Description
- Some users have been getting an IntegrityError 1217 when calling delete on an entry in a table with populated children
- The same user is able to manually delete each child table entry, and then delete the original entry once all children are removed
- The issue comes from the IntegrityError from `delete_quick` not being caught in the `cascade` function in `delete`, which is why all the children need deleted before can delete a table.
- The reason it's not getting caught is that datajoint is expecting the error code for ROW_IS_REFERENCED_2 (1451) but is instead getting the error code ROW_IS_REFERENCED (1217). The ROW_IS_REFERENCED error also returns less information about the failing table

### Reproducibility
- Linux
- Python Version: 3.9.16
- MySQL Version: 8.0.34
- MySQL Deployment Strategy: remote
- DataJoint Version: 0.14.1
- Minimum number of steps to reliably reproduce the issue:
Error only occurs for some users. Occurs when calling `TableName.delete({restriction}) ` on a table with child tables populated for the restriction

- Example error stack

> ---------------------------------------------------------------------------

> IntegrityError                            Traceback (most recent call last)
> Cell In[2], line 1
> ----> 1 Session().delete({"nwb_file_name":nwb_file_name})
> 
> File [~/mambaforge-pypy3/envs/spyglass/lib/python3.9/site-packages/datajoint/table.py:588](https://file+.vscode-resource.vscode-cdn.net/home/sambray/Documents/spyglass/notebooks/~/mambaforge-pypy3/envs/spyglass/lib/python3.9/site-packages/datajoint/table.py:588), in Table.delete(self, transaction, safemode, force_parts)
>     586 # Cascading delete
>     587 try:
> --> 588     delete_count = cascade(self)
>     589 except:
>     590     if transaction:
> 
> File [~/mambaforge-pypy3/envs/spyglass/lib/python3.9/site-packages/datajoint/table.py:506](https://file+.vscode-resource.vscode-cdn.net/home/sambray/Documents/spyglass/notebooks/~/mambaforge-pypy3/envs/spyglass/lib/python3.9/site-packages/datajoint/table.py:506), in Table.delete..cascade(table)
>     504 for _ in range(max_attempts):
>     505     try:
> --> 506         delete_count = table.delete_quick(get_count=True)
>     507     except IntegrityError as error:
>     508         match = foreign_key_error_regexp.match(error.args[0]).groupdict()
> 
> File [~/mambaforge-pypy3/envs/spyglass/lib/python3.9/site-packages/datajoint/table.py:465](https://file+.vscode-resource.vscode-cdn.net/home/sambray/Documents/spyglass/notebooks/~/mambaforge-pypy3/envs/spyglass/lib/python3.9/site-packages/datajoint/table.py:465), in Table.delete_quick(self, get_count)
>     460 """
>     461 Deletes the table without cascading and without user prompt.
>     462 If this table has populated dependent tables, this will fail.
>     463 """
>     464 query = "DELETE FROM " + self.full_table_name + self.where_clause()
> --> 465 self.connection.query(query)
>     466 count = (
>     467     self.connection.query("SELECT ROW_COUNT()").fetchone()[0]
>     468     if get_count
>     469     else None
>     470 )
>     471 self._log(query[:255])
> 
> File [~/mambaforge-pypy3/envs/spyglass/lib/python3.9/site-packages/datajoint/connection.py:346](https://file+.vscode-resource.vscode-cdn.net/home/sambray/Documents/spyglass/notebooks/~/mambaforge-pypy3/envs/spyglass/lib/python3.9/site-packages/datajoint/connection.py:346), in Connection.query(self, query, args, as_dict, suppress_warnings, reconnect)
>     344 cursor = self._conn.cursor(cursor=cursor_class)
>     345 try:
> --> 346     self._execute_query(cursor, query, args, suppress_warnings)
>     347 except errors.LostConnectionError:
>     348     if not reconnect:
> 
> File [~/mambaforge-pypy3/envs/spyglass/lib/python3.9/site-packages/datajoint/connection.py:302](https://file+.vscode-resource.vscode-cdn.net/home/sambray/Documents/spyglass/notebooks/~/mambaforge-pypy3/envs/spyglass/lib/python3.9/site-packages/datajoint/connection.py:302), in Connection._execute_query(cursor, query, args, suppress_warnings)
>     300         cursor.execute(query, args)
>     301 except client.err.Error as err:
> --> 302     raise translate_query_error(err, query)
> 
> File [~/mambaforge-pypy3/envs/spyglass/lib/python3.9/site-packages/datajoint/connection.py:300](https://file+.vscode-resource.vscode-cdn.net/home/sambray/Documents/spyglass/notebooks/~/mambaforge-pypy3/envs/spyglass/lib/python3.9/site-packages/datajoint/connection.py:300), in Connection._execute_query(cursor, query, args, suppress_warnings)
>     297         if suppress_warnings:
>     298             # suppress all warnings arising from underlying SQL library
>     299             warnings.simplefilter("ignore")
> --> 300         cursor.execute(query, args)
>     301 except client.err.Error as err:
>     302     raise translate_query_error(err, query)
> 
> File [~/mambaforge-pypy3/envs/spyglass/lib/python3.9/site-packages/pymysql/cursors.py:158](https://file+.vscode-resource.vscode-cdn.net/home/sambray/Documents/spyglass/notebooks/~/mambaforge-pypy3/envs/spyglass/lib/python3.9/site-packages/pymysql/cursors.py:158), in Cursor.execute(self, query, args)
>     154     pass
>     156 query = self.mogrify(query, args)
> --> 158 result = self._query(query)
>     159 self._executed = query
>     160 return result
> 
> File [~/mambaforge-pypy3/envs/spyglass/lib/python3.9/site-packages/pymysql/cursors.py:325](https://file+.vscode-resource.vscode-cdn.net/home/sambray/Documents/spyglass/notebooks/~/mambaforge-pypy3/envs/spyglass/lib/python3.9/site-packages/pymysql/cursors.py:325), in Cursor._query(self, q)
>     323 conn = self._get_db()
>     324 self._clear_result()
> --> 325 conn.query(q)
>     326 self._do_get_result()
>     327 return self.rowcount
> 
> File [~/mambaforge-pypy3/envs/spyglass/lib/python3.9/site-packages/pymysql/connections.py:549](https://file+.vscode-resource.vscode-cdn.net/home/sambray/Documents/spyglass/notebooks/~/mambaforge-pypy3/envs/spyglass/lib/python3.9/site-packages/pymysql/connections.py:549), in Connection.query(self, sql, unbuffered)
>     547     sql = sql.encode(self.encoding, "surrogateescape")
>     548 self._execute_command(COMMAND.COM_QUERY, sql)
> --> 549 self._affected_rows = self._read_query_result(unbuffered=unbuffered)
>     550 return self._affected_rows
> 
> File [~/mambaforge-pypy3/envs/spyglass/lib/python3.9/site-packages/pymysql/connections.py:779](https://file+.vscode-resource.vscode-cdn.net/home/sambray/Documents/spyglass/notebooks/~/mambaforge-pypy3/envs/spyglass/lib/python3.9/site-packages/pymysql/connections.py:779), in Connection._read_query_result(self, unbuffered)
>     777 else:
>     778     result = MySQLResult(self)
> --> 779     result.read()
>     780 self._result = result
>     781 if result.server_status is not None:
> 
> File [~/mambaforge-pypy3/envs/spyglass/lib/python3.9/site-packages/pymysql/connections.py:1157](https://file+.vscode-resource.vscode-cdn.net/home/sambray/Documents/spyglass/notebooks/~/mambaforge-pypy3/envs/spyglass/lib/python3.9/site-packages/pymysql/connections.py:1157), in MySQLResult.read(self)
>    1155 def read(self):
>    1156     try:
> -> 1157         first_packet = self.connection._read_packet()
>    1159         if first_packet.is_ok_packet():
>    1160             self._read_ok_packet(first_packet)
> 
> File [~/mambaforge-pypy3/envs/spyglass/lib/python3.9/site-packages/pymysql/connections.py:729](https://file+.vscode-resource.vscode-cdn.net/home/sambray/Documents/spyglass/notebooks/~/mambaforge-pypy3/envs/spyglass/lib/python3.9/site-packages/pymysql/connections.py:729), in Connection._read_packet(self, packet_type)
>     727     if self._result is not None and self._result.unbuffered_active is True:
>     728         self._result.unbuffered_active = False
> --> 729     packet.raise_for_error()
>     730 return packet
> 
> File [~/mambaforge-pypy3/envs/spyglass/lib/python3.9/site-packages/pymysql/protocol.py:221](https://file+.vscode-resource.vscode-cdn.net/home/sambray/Documents/spyglass/notebooks/~/mambaforge-pypy3/envs/spyglass/lib/python3.9/site-packages/pymysql/protocol.py:221), in MysqlPacket.raise_for_error(self)
>     219 if DEBUG:
>     220     print("errno =", errno)
> --> 221 err.raise_mysql_exception(self._data)
> 
> File [~/mambaforge-pypy3/envs/spyglass/lib/python3.9/site-packages/pymysql/err.py:143](https://file+.vscode-resource.vscode-cdn.net/home/sambray/Documents/spyglass/notebooks/~/mambaforge-pypy3/envs/spyglass/lib/python3.9/site-packages/pymysql/err.py:143), in raise_mysql_exception(data)
>     141 if errorclass is None:
>     142     errorclass = InternalError if errno < 1000 else OperationalError
> --> 143 raise errorclass(errno, errval)
> 
> IntegrityError: (1217, 'Cannot delete or update a parent row: a foreign key constraint fails')

### Expected Behavior
A deletion of the row entry and all dependent entries in child tables

### Additional Research and Context
I'm not entirely sure where the change is in MySQL, but this seems related to this post [here](https://dba.stackexchange.com/questions/282009/mysql-same-db-same-query-different-users-different-error-messages
)

**Comment by lfrank** [comment]
@dimitri-yatsenko Just checking in on this, as it's a bit of a challenge for users not to be able to delete entries from our comment tables. Any ideas?

**Comment by dimitri-yatsenko** [comment]
fixed in #1112

**Comment by CBroz1** [comment]
Unfortunately, errors persist for users with insufficient privileges. I did not see the error when testing with the first account listed below, but I do see it with the second.
```sql
mysql> show grants for 'cbroz';
+------------------------------------------------------------+
| Grants for cbroz@%                                         |
+------------------------------------------------------------+
| GRANT ALL PRIVILEGES ON `%`.* TO `cbroz`@`%`               |
...
mysql> show grants for 'cbroz-basic';
+------------------------------------------------------------+
| Grants for cbroz-basic@%                                   |
+------------------------------------------------------------+
| GRANT SELECT ON `%`.* TO `cbroz-basic`@`%`                 |
```

When DataJoint catches MySQL 8 error `1217`, MySQL is not giving sufficient information to continue the cascade:
```python
Cell In[4], line 1
----> 1 from spyglass.common import IntervalList; (IntervalList & 'nwb_file_name LIKE "SC3820230606_.nwb%"').delete()

File ~/wrk/datajoint-python/datajoint/table.py:586, in Table.delete(self, transaction, safemode, force_parts)
    584 # Cascading delete
    585 try:
--> 586     delete_count = cascade(self)
    587 except:
    588     if transaction:

File ~/wrk/datajoint-python/datajoint/table.py:506, in Table.delete.<locals>.cascade(table)
    504     delete_count = table.delete_quick(get_count=True)
    505 except IntegrityError as error:
--> 506     match = foreign_key_error_regexp.match(error.args[0]).groupdict()
    507     if "`.`" not in match["child"]:  # if schema name missing, use table
    508         match["child"] = "{}.{}".format(
    509             table.full_table_name.split(".")[0], match["child"]
    510         )

AttributeError: 'NoneType' object has no attribute 'groupdict'
```

What would you suggest @dimitri-yatsenko? Is there a way to continue the cascade without granting additional privileges for the user?

**Comment by dimitri-yatsenko** [comment]
@CBroz1 Thanks for your patience. Is this still a problem. I am in a good place to fix this.

**Comment by dimitri-yatsenko** [comment]
@samuelbray32 Thanks for your patience. Is this still a problem? I am in a good place to fix this.

**Comment by CBroz1** [comment]
Thanks for your attention to this @dimitri-yatsenko. Yes, we've unfortunately had to elevate the permissions of many users as a result of this issue. When I last tested, I was not able to replicate in a mysql 8 docker container, so I suspect it is related to the upgrade process for 5 -> 8

I've posted to multiple forums without solid leads
- [Stack Exchange](https://dba.stackexchange.com/questions/334167/error-1216-not-1451-despite-reference-privilege-on-mysql-8)
- [Stack Overflow](https://stackoverflow.com/questions/78044502/error-1217-vs-1452-still-less-verbose-despite-grant-all?noredirect=1#comment137594975_78044502)
- [MySQL bugs forum](https://bugs.mysql.com/bug.php?id=99336)

**Comment by dimitri-yatsenko** [comment]
Thank you. We have improved the error message in the upcoming release but the problems remains related to insufficient privileges and how MySQL handles them.

**Comment by CBroz1** [comment]
> Feel free to reach out again for more details/minimal reproducible example.

Hi @Hendriela - I was starting to worry our database was the only one to experience this issue! I tried on and off for some time, but I wasn't able to create a minimal reproduction that included a low-privilege user (a) attempting to delete an entry on a schema for which they had privileges and (b) getting the low-verbosity error. Is that something you're able to do?

Even in my [attempted replication repo](https://github.com/CBroz1/datajoint_permission_demo), results were inconsistent. We have had to resort to granting `ALL` to most users for our production database

**Comment by CBroz1** [comment]
Thanks @Hendriela! 

I'm having trouble replicating the error with the schema you provided. I put together the script below to spin up a container, insert the data, and then run each of the deletes you listed. 

| Del # | Alone | Master | Part | Downstream | Expected Err |
| -------: | :-----------: | :-------------: | :---------: | :---------------------: | :-----------------: |
|  1.      |      X        |                   |              |                            |                        |
|  2.      |                |        X         |              |                            |                        |
|  3.      |                |        X         |     X       |                            |         X             |
|  4.      |                |        X         |              |          X                |         X             |
|  5.      |                |        X         |     X       |          X                |         X             |

- Do you know which MySQL patch you're using?
- Does the data insert below map on to what you ran?

<details><summary>Script</summary>

```python
# ------------------------ Constants and Configuration ------------------------

CONTAINER_NAME = "test_priv"
MYSQL_IMAGE = "mysql:8.0.34"
PORT = 3306
ROOT_PW = "tutorial"
SCHEMA = "test_schema"
USER = "test_user"
USER_PW = "password"
DJ_LOG_LEVEL = "CRITICAL"
SHARED_CONFIG = {"database.host": "localhost", "database.port": PORT}
ROOT_CONFIG = {"user": "root", "password": ROOT_PW, "reset": True}
USER_CONFIG = {"user": USER, "password": USER_PW, "reset": True}

# --------------------- Setup MySQL Container with Docker ---------------------

import time  # noqa: E402

import docker  # noqa: E402


def remove_container(client: docker.DockerClient):
    try:
        container = client.containers.get(CONTAINER_NAME)
        print(f"Stopping/removing container: {CONTAINER_NAME}")
        container.stop()
        container.remove()
    except docker.errors.NotFound:
        print(f"No existing container named '{CONTAINER_NAME}'")


def start_mysql_container(client):
    print(f"Starting MySQL container   : {CONTAINER_NAME}")
    container = client.containers.run(
        image=MYSQL_IMAGE,
        name=CONTAINER_NAME,
        environment={"MYSQL_ROOT_PASSWORD": ROOT_PW},
        ports={"3306/tcp": PORT},
        detach=True,
    )
    return container


def wait_for_mysql(container, timeout=30):
    print(f"Waiting for container      : {CONTAINER_NAME}")
    for _ in range(timeout):
        try:
            exit_code, output = container.exec_run(
                f"mysqladmin ping -uroot -p{ROOT_PW}"
            )
            if b"mysqld is alive" in output:
                return
        except Exception:
            pass
        time.sleep(1)
    raise TimeoutError("MySQL did not become ready in time.")


def print_mysql_version(container):
    exit_code, output = container.exec_run(
        [
            "mysql",
            "-N",
            "-s",
            "-uroot",
            f"-p{ROOT_PW}",
            "-e",
            "SELECT VERSION();",
        ]
    )
    print(f"MySQL version              : {output.decode().splitlines()[-1]}")


def grant_privileges(container):
    sql = f"""
    CREATE USER IF NOT EXISTS '{USER}'@'%' IDENTIFIED BY '{USER_PW}';
    GRANT CREATE VIEW, SHOW VIEW, INDEX, TRIGGER ON {SCHEMA}.* TO '{USER}'@'%';
    FLUSH PRIVILEGES;
    """
    print(f"Granting privileges to     : {USER}")
    container.exec_run(cmd=["mysql", "-uroot", f"-p{ROOT_PW}", "-e", sql])


# === Docker Startup ===
if __name__ == "__main__":
    client = docker.from_env()
    _ = remove_container(client)
    container = start_mysql_container(client)
    _ = wait_for_mysql(container)
    _ = print_mysql_version(container)
    _ = grant_privileges(container)


# ------------------------------- Run DataJoint -------------------------------

import sys  # noqa: E402

import datajoint as dj  # noqa: E402

print(f"Python Version             : {sys.version.split()[0]}")
print(f"DataJoint Version          : {dj.__version__}")

dj.config = SHARED_CONFIG
dj.logger.setLevel(DJ_LOG_LEVEL)
conn = dj.conn(**ROOT_CONFIG)
print(f"Declaring tables as        : {conn.get_user()}")

schema = dj.schema(SCHEMA, create_tables=True)


@schema
class TestAlone(dj.Manual):
    definition = """
    alone_pk: int unsigned
    """


@schema
class TestMaster(dj.Manual):
    definition = """
    master_id: int unsigned
    """

    class TestPart(dj.Part):
        definition = """
        -> master
        ---
        part_sk: int unsigned
        """


@schema
class TestDownstream(dj.Manual):
    definition = """
    -> TestMaster
    """


conn.close()


def insert_test_data_as_root():
    """Insert test data into the tables."""
    conn = dj.conn(**ROOT_CONFIG)
    print(f"Inserting data as          : {conn.get_user()}")
    TestAlone.insert([[0], [1]], skip_duplicates=True)
    TestMaster.insert([[4], [5], [6], [7], [8]], skip_duplicates=True)
    TestMaster.TestPart.insert([[5, 10], [7, 20]], skip_duplicates=True)
    TestDownstream.insert([[6], [7], [8]], skip_duplicates=True)
    conn.close()


def delete_test_data_as_user():
    """Delete test data as a non-root user."""

    conn = dj.conn(**USER_CONFIG)
    print(f"Deleting entries as        : {conn.get_user()}")

    print("  1. Delete from TestAlone...")
    assert len(TestAlone & "alone_pk=0") == 1
    (TestAlone & "alone_pk=0").delete(safemode=False)
    assert len(TestAlone & "alone_pk=0") == 0

    print("  2. Delete from TestMaster, not TestPart/TestDownstream...")
    assert len(TestMaster & "master_id=4") == 1
    assert len(TestMaster.TestPart & "master_id=4") == 0
    (TestMaster & "master_id=4").delete(safemode=False)
    assert len(TestMaster & "master_id=4") == 0

    print("  3. Delete from TestMaster/TestPart, not TestDownstream...")
    assert len(TestMaster.TestPart & "master_id=5") == 1
    (TestMaster & "master_id=5").delete(safemode=False)
    assert len(TestMaster.TestPart & "master_id=5") == 0

    print("  4. Delete from TestMaster/TestDownstream, not TestPart...")
    assert len(TestMaster * TestDownstream & "master_id=6") == 1
    assert len(TestMaster.TestPart & "master_id=6") == 0
    (TestMaster & "master_id=6").delete(safemode=False)
    assert len(TestDownstream & "master_id=6") == 0

    print("  5. Delete from TestMaster/TestPart, and TestDownstream...")
    assert len(TestMaster.TestPart * TestDownstream & "master_id=7") == 1
    (TestMaster & "master_id=7").delete(safemode=False)
    assert len(TestMaster & "master_id=7") == 0

    print("Passed all deletion tests!")

    conn.close()


if __name__ == "__main__":
    insert_test_data_as_root()
    delete_test_data_as_user()
```

</details>

<details><summary>Output</summary>

```python
run pipeline-hendrik.py
Stopping/removing container: test_priv
Starting MySQL container   : test_priv
Waiting for container      : test_priv
MySQL version              : 8.0.34
Granting privileges to     : test_user
Python Version             : 3.10.16
DataJoint Version          : 0.13.7
Declaring tables as        : root@172.17.0.1
Inserting data as          : root@172.17.0.1
Deleting entries as        : test_user@172.17.0.1
  1. Delete from TestAlone...
  2. Delete from TestMaster, not TestPart/TestDownstream...
  3. Delete from TestMaster/TestPart, not TestDownstream...
  4. Delete from TestMaster/TestDownstream, not TestPart...
  5. Delete from TestMaster/TestPart, and TestDownstream...
Passed all deletion tests!
```

</details>

I agree that all this could be circumvented it DataJoint did not rely on parsing verbose error messages to continue the cascade. From my various forum posts, I could never get a straight answer as so why MySQL would return the less verbose error when the user had permission to the relevant table

**Comment by Hendriela** [comment]
I tried to look at your tests. Bear with me since I am far from an expert software engineer like you are, so maybe I am misinterpreting the code a bit...

The setup, table structure and inserts/deletes seem correct to me, similar to what I tried.

> def grant_privileges(container):
        sql = f"""
        CREATE USER IF NOT EXISTS '{USER}'@'%' IDENTIFIED BY '{USER_PW}';
        GRANT CREATE VIEW, SHOW VIEW, INDEX, TRIGGER ON {SCHEMA}.* TO '{USER}'@'%';
        FLUSH PRIVILEGES;
        """
        print(f"Granting privileges to     : {USER}")
        container.exec_run(cmd=["mysql", "-uroot", f"-p{ROOT_PW}", "-e", sql])

Your `grant_privileges()` seems to me to only only grant `CREATE VIEW, SHOW VIEW, INDEX, TRIGGER`, but not `DELETE`, and yet `test_user` is able to delete entries? Maybe I am missing something?

In my setup, these four privileges you are granting here (together with basic ones like `SELECT`, `REFERENCES`, `DELETE`) are necessary for successful `delete()` calls in all of the different `delete` scenarios you and I tried. So, if you are granting your `test_user` those privileges, the deletes should go through as expected. In this sense, I would say your test was successful, as no errors should be expected here?

My point was that if any one of the `CREATE VIEW, SHOW VIEW, INDEX, TRIGGER` privileges are missing, `test_user` cannot cascade deletes anymore (resulting in the "expected" errors from your table, expected in the sense that they would replicate the bug), even though these privileges have nothing to do with cascading or deleting in my eyes.

What happens if you don't grant your `test_user` one or more of those extra privileges? Do the dependent deletes still go through?

**Comment by ktshah04** [comment]
We have also been seeing this issue frequently. It seems like unless you have full permissions, cascade deletes do not work. 

Just to recap what we see

if I run a delete (with full permissions on all schemas) it cascades correctly

```
(Session & "subject_id = '20226'").delete()

[2025-05-28 20:36:17,745][INFO]: Deleting 12 rows from `emgimu_sessions`.`__firebase_session__app_depth_video`
[2025-05-28 20:36:17,829][INFO]: Deleting 12 rows from `emgimu_sessions`.`__firebase_session__app_video`
[2025-05-28 20:36:17,878][INFO]: Deleting 12 rows from `emgimu_sessions`.`__firebase_session`
[2025-05-28 20:36:17,904][INFO]: Deleting 12 rows from `emgimu_sessions`.`session__firebase_session_info`
[2025-05-28 20:36:17,932][INFO]: Deleting 1 rows from `emgimu_sessions`.`session`
```

When another user tries this, who has all permissions except DROP and GRANT OPTION on the emgimu_sessions schema (which is the only relevant schema for this delete)

They get the GroupDict error 

```
---------------------------------------------------------------------------
IntegrityError                            Traceback (most recent call last)
File ~/workspace/.venv/lib/python3.11/site-packages/datajoint/table.py:519, in Table.delete.<locals>.cascade(table)
    518 try:
--> 519     delete_count = table.delete_quick(get_count=True)
    520 except IntegrityError as error:
File ~/workspace/.venv/lib/python3.11/site-packages/datajoint/table.py:474, in Table.delete_quick(self, get_count)
    473 query = "DELETE FROM " + self.full_table_name + self.where_clause()
--> 474 self.connection.query(query)
    475 count = (
    476     self.connection.query("SELECT ROW_COUNT()").fetchone()[0]
    477     if get_count
    478     else None
    479 )
File ~/workspace/.venv/lib/python3.11/site-packages/datajoint/connection.py:343, in Connection.query(self, query, args, as_dict, suppress_warnings, reconnect)
    342 try:
--> 343     self._execute_query(cursor, query, args, suppress_warnings)
    344 except errors.LostConnectionError:
File ~/workspace/.venv/lib/python3.11/site-packages/datajoint/connection.py:299, in Connection._execute_query(cursor, query, args, suppress_warnings)
    298 except client.err.Error as err:
--> 299     raise translate_query_error(err, query)
IntegrityError: Cannot delete or update a parent row: a foreign key constraint fails
During handling of the above exception, another exception occurred:
AttributeError                            Traceback (most recent call last)
Cell In[61], line 1
----> 1 (Session &  'subject_id = "20226"').delete()
File ~/workspace/.venv/lib/python3.11/site-packages/datajoint/table.py:623, in Table.delete(self, transaction, safemode, force_parts, force_masters)
    621 # Cascading delete
    622 try:
--> 623     delete_count = cascade(self)
    624 except:
    625     if transaction:
File ~/workspace/.venv/lib/python3.11/site-packages/datajoint/table.py:521, in Table.delete.<locals>.cascade(table)
    519     delete_count = table.delete_quick(get_count=True)
    520 except IntegrityError as error:
--> 521     match = foreign_key_error_regexp.match(error.args[0]).groupdict()
    522     # if schema name missing, use table
    523     if "`.`" not in match["child"]:
AttributeError: 'NoneType' object has no attribute 'groupdict'
```

The way we have been getting around this without giving full permissions is to do the deletes in reverse order like this example

```
kin_rec_keys = (KinematicReconstruction & cal_key).fetch("KEY")
(KinematicReconstruction.Trial & kin_rec_keys).delete(force=True)

kin_rec_keys = (KinematicReconstruction & cal_key).fetch("KEY")
(KinematicReconstruction & kin_rec_keys).delete()

session_cal_rec_keys = (SessionCalibration.Recordings & cal_key).fetch("KEY")
(SessionCalibration.Recordings & session_cal_rec_keys).delete(force=True)

session_cal_group_keys = (SessionCalibration.Grouping & cal_key).fetch("KEY")
(SessionCalibration().Grouping & session_cal_group_keys).delete(force=True)

cal_rec_keys = (CalibratedRecording & cal_key).fetch("KEY")
(CalibratedRecording & cal_rec_keys).delete()

(Calibration & cal_key).delete()
```

After updating to 0.14.6, I see that the groupdict error has been updated to be 

```
File ~/.local/lib/python3.11/site-packages/datajoint/table.py:631, in Table.delete(self, transaction, safemode, force_parts, force_masters)
    629 # Cascading delete
    630 try:
--> [631](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f6973725f6465765f6b73686168227d-0040ssh-002dremote-002bjc-002dcompute01-002eric-002eorg.vscode-resource.vscode-cdn.net/home/vscode/workspace/notebooks/~/.local/lib/python3.11/site-packages/datajoint/table.py:631)     delete_count = cascade(self)
    632 except:
    633     if transaction:

File ~/.local/lib/python3.11/site-packages/datajoint/table.py:525, in Table.delete.<locals>.cascade(table)
    523 match = foreign_key_error_regexp.match(error.args[0])
    524 if match is None:
--> [525](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f6973725f6465765f6b73686168227d-0040ssh-002dremote-002bjc-002dcompute01-002eric-002eorg.vscode-resource.vscode-cdn.net/home/vscode/workspace/notebooks/~/.local/lib/python3.11/site-packages/datajoint/table.py:525)     raise DataJointError(
    526         "Cascading deletes failed because the error message is missing foreign key information."
    527         "Make sure you have REFERENCES privilege to all dependent tables."
    528     ) from None
    529 match = match.groupdict()
    530 # if schema name missing, use table

DataJointError: Cascading deletes failed because the error message is missing foreign key information.Make sure you have REFERENCES privilege to all dependent tables.
```

While this is more informative than the groupdict error, it would be even more helpful if the tables missing privileges were returned in some way. Or even just the schema name.

**Comment by dimitri-yatsenko** [comment]
## Analysis: MySQL Error 1217 vs 1451 on Cascade Delete

### Problem Summary

When deleting rows with foreign key dependencies, MySQL returns different error codes depending on user privileges:

| Error Code | Name | Info Provided | When |
|------------|------|---------------|------|
| **1451** | ROW_IS_REFERENCED_2 | Full details (child table, constraint, columns) | User has sufficient privileges |
| **1217** | ROW_IS_REFERENCED | Minimal ("a foreign key constraint fails") | User lacks privileges |

DataJoint's cascade delete relies on parsing the error message to identify which child table is blocking the delete. With error 1217, there's insufficient information to continue.

### Root Cause

MySQL intentionally hides detailed error information from users without sufficient privileges (security feature). The required privileges appear to be:
- `SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, REFERENCES` (basic)
- **Plus**: `CREATE VIEW, SHOW VIEW, INDEX, TRIGGER` (for verbose errors)

### Current Status in DataJoint 2.0

The error handling has been **improved** but not fully resolved:

```python
# src/datajoint/table.py:853-858
match = foreign_key_error_regexp.match(error.args[0])
if match is None:
    raise DataJointError(
        "Cascading deletes failed because the error message is missing foreign key information."
        "Make sure you have REFERENCES privilege to all dependent tables."
    ) from None
```

**Before**: Crashed with `AttributeError: 'NoneType' object has no attribute 'groupdict'`  
**After**: Clear error message pointing to privilege issue

### Possible Solutions

1. **Document required privileges** (quick fix)
   - Update docs to specify all required privileges for cascade delete

2. **Use dependency graph instead of error parsing** (robust fix)
   - DataJoint already tracks dependencies via `INFORMATION_SCHEMA`
   - Could pre-compute delete order from dependency graph rather than relying on error messages
   - More work but would eliminate privilege dependency

3. **Hybrid approach**
   - Try error-based cascade first
   - On error 1217, fall back to dependency graph approach

### Recommendation

The issue is **partially addressed** in 2.0 (better error message) but the underlying problem remains for users with restricted privileges. For full resolution, consider implementing dependency-graph-based cascade delete as an alternative path when error parsing fails.
